filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true
setup.ilm.enabled: false
output.kafka:
  hosts: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  ssl.certificate_authorities: /certs/elk-ca.crt
  ssl.enabled: true
  ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]
  ssl.certificate: "/certs/root.crt"
  ssl.key: "/certs/root.key"
  topic: "elk-test"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

logging.json: true
logging.metrics.enabled: false
